language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install --upgrade setuptools
  - pip install -e .
  - pip install -e ".[test]"
  - pip install codecov

script:
  - py.test --cov=piffle

after_success:
  - codecov
