coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      core:  # custom target for core package
        target: 95%
        paths:
          - "src/piffle/"
      tests:  # 100% coverage for test files
        target: 100%
        paths:
          - "tests/"  # only include coverage in tests folder
#      experimental:
#        target: 45%
#        paths:
#          - "src/piffle/iiif_dataclasses"
#          - "src/piffle/load_presentation.py"
#          - "src/piffle/utils.py"
