name: Check Ruff linter + formatter
on:
  # Run on pull requests to develop or main
  pull_request:
    branches: [develop, main]
  # Allow running manually
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  # Cancel existing job(s) for workflow when a new one is queued
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    name: Ruff check and formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - name: Run Ruff linter
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b  # v4.0.0
        with:
          args: "check --output-format=github"
      - name: Run Ruff formatter
        # NOTE: ruff format does not currently support github output format
        run: ruff format --check --diff
        # Check formatting even if the previous step failed
        if: always()
