name: Check Ruff linter + formatter
on:
  # Run on pull requests to develop or main
  pull_request:
    branches: [develop, main]
  # Allow running manually
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  # Cancel existing job(s) for workflow when a new one is queued
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    name: Run Ruff checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false
      - name: Run Ruff linter
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b  #v4.0.0
        with:
          args: "check --output-format=github"
      - name: Run Ruff formatter
        # NOTE: ruff format does not currently support github output format
        run: ruff format --check --diff
        # Check formatting even if the previous step failed
        if: always()
